import Config

config :cors_plug,
  origin: ["https://streaming.com"],
  max_age: 86400,
  methods: ["GET", "POST"]

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :streaming_backend, StreamingBackendWeb.Endpoint,
url: [scheme: "https", host: "streaming.com", port: 443],
  cache_static_manifest: "priv/static/cache_manifest.json",
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  https: [
    port: 4001,
    cipher_suite: :strong,
    otp_app: :streaming_backend,
    keyfile: "priv/streaming.key",
    certfile: "priv/streaming.crt",
  ]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: StreamingBackend.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
